{
  "formatVersion": "1.1",
  "component": {
    "group": "com.wogoo.android",
    "module": "backgroudCompat",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.noober.background",
          "module": "core",
          "version": {
            "requires": "1.6.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "backgroudCompat-1.0.0.aar",
          "url": "backgroudCompat-1.0.0.aar",
          "size": 10303,
          "sha512": "87092ee6d45832966f099c7b4cbbf811bfe5a9b8c00d6cd098e4d595ae6b3a0c84681f517d6936c6e5f9e786ca726ecad686aa3238a963497ae332cfcd8dafe9",
          "sha256": "6bfd076e363ccd80782b619aca4068c18a76187d510b81ea261a46d29fa8d041",
          "sha1": "f4f41659ee1210d10479e9e97a9437b554eea770",
          "md5": "9d3d4612caf59cc70ef31cacae99c6c9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.wogoo.android",
          "module": "uimode",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.noober.background",
          "module": "core",
          "version": {
            "requires": "1.6.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "backgroudCompat-1.0.0.aar",
          "url": "backgroudCompat-1.0.0.aar",
          "size": 10303,
          "sha512": "87092ee6d45832966f099c7b4cbbf811bfe5a9b8c00d6cd098e4d595ae6b3a0c84681f517d6936c6e5f9e786ca726ecad686aa3238a963497ae332cfcd8dafe9",
          "sha256": "6bfd076e363ccd80782b619aca4068c18a76187d510b81ea261a46d29fa8d041",
          "sha1": "f4f41659ee1210d10479e9e97a9437b554eea770",
          "md5": "9d3d4612caf59cc70ef31cacae99c6c9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backgroudCompat-1.0.0-sources.jar",
          "url": "backgroudCompat-1.0.0-sources.jar",
          "size": 4380,
          "sha512": "dfd19fab00e127123b41e4110f21e7d977f78bcd1dd1a52b43f5b578e5e3117d040f63832211c6611d54c5513eab4769c75e5cebaed47e970ffe6d266c5cde19",
          "sha256": "e266f111ff76abe942070ac13b53d44db5b9e7b3589ff1b0049d2fed2e1a0171",
          "sha1": "6487c3ac242ff07613475fbd9e0b0f9fa2bc4913",
          "md5": "fb1d69f5664014f004637f5c77ab57f6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backgroudCompat-1.0.0-javadoc.jar",
          "url": "backgroudCompat-1.0.0-javadoc.jar",
          "size": 279373,
          "sha512": "e82668930f0a7a738418b2a9f36f174f149c16ffe0e057ac6ea0ba6c185825245ab90bcfedd2417035983abcda8b0a4c1292d132ccc4f736c2d084bfd6f7a387",
          "sha256": "17ab37cdb48937c0f93dd9d4586eb4148a4c3af92b0b95f7147f37f98bbbe177",
          "sha1": "80ae31550b61bc32f5e1b4f1644e30ad0048b6f7",
          "md5": "12fc072339a556597acee98fdfb7c56b"
        }
      ]
    }
  ]
}
