{
  "formatVersion": "1.1",
  "component": {
    "group": "com.wogoo.android",
    "module": "uimode",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "uimode-1.0.0.aar",
          "url": "uimode-1.0.0.aar",
          "size": 86761,
          "sha512": "15c214cf56b8f9e83bad17352889846d611d3f10ec95a439fcbdf11c21c33862ff1245d3969873658cbcdccb368d80fe3088eb98b9aba79a4e2f4e40eca4d939",
          "sha256": "32569ee6fe01755f822737d783b2081843c5a85328bc1a2a403faeda35f652d9",
          "sha1": "cf2a9b31c3287c20200625f6def5bec7f762e225",
          "md5": "29711e220166a6de55ac472d24044b44"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "uimode-1.0.0.aar",
          "url": "uimode-1.0.0.aar",
          "size": 86761,
          "sha512": "15c214cf56b8f9e83bad17352889846d611d3f10ec95a439fcbdf11c21c33862ff1245d3969873658cbcdccb368d80fe3088eb98b9aba79a4e2f4e40eca4d939",
          "sha256": "32569ee6fe01755f822737d783b2081843c5a85328bc1a2a403faeda35f652d9",
          "sha1": "cf2a9b31c3287c20200625f6def5bec7f762e225",
          "md5": "29711e220166a6de55ac472d24044b44"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "uimode-1.0.0-sources.jar",
          "url": "uimode-1.0.0-sources.jar",
          "size": 121451,
          "sha512": "cf83a75762c01460037d997c2d57759e67033d206aaeb63fe399482548c45783cea2235f3b9f482a1c4c09a270d761ca286a56e2703b9714d3b943527e3ec1eb",
          "sha256": "3a502848a44a847956a57706ea05dc77e15c726d3c6623622f10ebbe6d6d9e11",
          "sha1": "81938a872b439544f2e30ae1e94150a705386b99",
          "md5": "80b1eee17adcf8b4cccbddca5a7e58e6"
        }
      ]
    }
  ]
}
