{
  "formatVersion": "1.1",
  "component": {
    "group": "com.wogoo.android",
    "module": "backgroundCompat",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.noober.background",
          "module": "core",
          "version": {
            "requires": "1.6.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "backgroundCompat-1.0.0.aar",
          "url": "backgroundCompat-1.0.0.aar",
          "size": 10313,
          "sha512": "4fc50d17b305ada592d47ca9794d680999c6ef24abeeba5f7721c583c72ad24e9049a931273a28ea204ef3a522d764ba3643631b3b6d537f613aa2355a5b57aa",
          "sha256": "5347fa45ccbe2a8577c7585bcfe5770a6b5715d05f2f37c76019cf26856bee40",
          "sha1": "fb085f03d02efb5176c14cb92ea2b478eb56d066",
          "md5": "0a3585a3f126ce530def3eb0150fc58e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.wogoo.android",
          "module": "uimode",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.noober.background",
          "module": "core",
          "version": {
            "requires": "1.6.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "backgroundCompat-1.0.0.aar",
          "url": "backgroundCompat-1.0.0.aar",
          "size": 10313,
          "sha512": "4fc50d17b305ada592d47ca9794d680999c6ef24abeeba5f7721c583c72ad24e9049a931273a28ea204ef3a522d764ba3643631b3b6d537f613aa2355a5b57aa",
          "sha256": "5347fa45ccbe2a8577c7585bcfe5770a6b5715d05f2f37c76019cf26856bee40",
          "sha1": "fb085f03d02efb5176c14cb92ea2b478eb56d066",
          "md5": "0a3585a3f126ce530def3eb0150fc58e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backgroundCompat-1.0.0-sources.jar",
          "url": "backgroundCompat-1.0.0-sources.jar",
          "size": 4380,
          "sha512": "dfd19fab00e127123b41e4110f21e7d977f78bcd1dd1a52b43f5b578e5e3117d040f63832211c6611d54c5513eab4769c75e5cebaed47e970ffe6d266c5cde19",
          "sha256": "e266f111ff76abe942070ac13b53d44db5b9e7b3589ff1b0049d2fed2e1a0171",
          "sha1": "6487c3ac242ff07613475fbd9e0b0f9fa2bc4913",
          "md5": "fb1d69f5664014f004637f5c77ab57f6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backgroundCompat-1.0.0-javadoc.jar",
          "url": "backgroundCompat-1.0.0-javadoc.jar",
          "size": 279376,
          "sha512": "bcc462b8540d5381f85943dd11ae0f2436b18d5f5a61604ab00add83edf8a4f7b01ca676e5e4f2e8feb0b04552c1f53f8b0a9caf7bced1498079acb388f23cf1",
          "sha256": "9bb094163daa4512a522be745e3f32876608293645739b5a365411c89bed108d",
          "sha1": "b0d4f1a1062dd3f7f911165a53749a2b278fb25f",
          "md5": "af9d75f440e271fb6b4a4a6cd5ec0948"
        }
      ]
    }
  ]
}
