{
  "formatVersion": "1.1",
  "component": {
    "group": "com.wogoo.android",
    "module": "background-uimode",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.wogoo.android",
          "module": "backround",
          "version": {
            "requires": "1.6.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "background-uimode-1.0.0.aar",
          "url": "background-uimode-1.0.0.aar",
          "size": 50388,
          "sha512": "86d3987a73c0822e8232628a46894a8f25bd6589c089bff51a25a076efa4439784559db30d3367b8650095c243f534a75306e26ccf50e49f8341ae4fffb64251",
          "sha256": "ddb78f292aa509cc52727b06c6a7b939c199851df696557a1bfdae67ef714d02",
          "sha1": "16cfff24dd6dc471408d793e97e6916c9c987a07",
          "md5": "a307d706ba023333fd68c55718f94744"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.wogoo.android",
          "module": "uimode",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.wogoo.android",
          "module": "backround",
          "version": {
            "requires": "1.6.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "background-uimode-1.0.0.aar",
          "url": "background-uimode-1.0.0.aar",
          "size": 50388,
          "sha512": "86d3987a73c0822e8232628a46894a8f25bd6589c089bff51a25a076efa4439784559db30d3367b8650095c243f534a75306e26ccf50e49f8341ae4fffb64251",
          "sha256": "ddb78f292aa509cc52727b06c6a7b939c199851df696557a1bfdae67ef714d02",
          "sha1": "16cfff24dd6dc471408d793e97e6916c9c987a07",
          "md5": "a307d706ba023333fd68c55718f94744"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "background-uimode-1.0.0-sources.jar",
          "url": "background-uimode-1.0.0-sources.jar",
          "size": 26311,
          "sha512": "ab0cc937ba435964ea5a6e0c473657f3196882c670cdbfcc48c2e6a51e23f36aa7e35b643bd08a425292366416f5e93c6bdac3a6f1a957b7b2658f70a893219f",
          "sha256": "a24b20bfe217a03086f138e02fb286c25ca433a2542731d517579f7c120572eb",
          "sha1": "775032a0326bcf400e5c97cf642f8977ac6aed1e",
          "md5": "4006a8fbe251c94766430a75a2b249d2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "background-uimode-1.0.0-javadoc.jar",
          "url": "background-uimode-1.0.0-javadoc.jar",
          "size": 362811,
          "sha512": "1cc59bb525b88e25467e357a84d066ca995520e10c816f5f41a2b173edf966fb5c19433e378913001fa8411b3742362613a3f2c0ae90d36f86f57b97049c1a2e",
          "sha256": "b25f82f3ddad034a2d970b2e91be6373838518a891fcd0befec3906f57e51c21",
          "sha1": "f41022697af2c65551e5fcdd464d9895984ee523",
          "md5": "c36858aaf8b54bf467975a40c133405d"
        }
      ]
    }
  ]
}
