{
  "formatVersion": "1.1",
  "component": {
    "group": "com.wogoo.android",
    "module": "background-uimode",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.wogoo.android",
          "module": "backround",
          "version": {
            "requires": "1.6.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "background-uimode-1.0.0.aar",
          "url": "background-uimode-1.0.0.aar",
          "size": 50761,
          "sha512": "f0b2d1694b364775937dca971d62caa90ef2d4fdeb77b21bd831180b3090a6a71ef5282ba91d196d98e08168e0536bba193f94b79974d61ed6bc714b465ca8b4",
          "sha256": "7756087eb7a545353236119fe725d7b0870c85b1f7ee358fb2d4a3166a8a2373",
          "sha1": "f12e352e29721b3f3c5823ce86538aee003d4df2",
          "md5": "76bf55d2c55a3bed51d4b3227e401f02"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.wogoo.android",
          "module": "uimode",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.wogoo.android",
          "module": "backround",
          "version": {
            "requires": "1.6.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "background-uimode-1.0.0.aar",
          "url": "background-uimode-1.0.0.aar",
          "size": 50761,
          "sha512": "f0b2d1694b364775937dca971d62caa90ef2d4fdeb77b21bd831180b3090a6a71ef5282ba91d196d98e08168e0536bba193f94b79974d61ed6bc714b465ca8b4",
          "sha256": "7756087eb7a545353236119fe725d7b0870c85b1f7ee358fb2d4a3166a8a2373",
          "sha1": "f12e352e29721b3f3c5823ce86538aee003d4df2",
          "md5": "76bf55d2c55a3bed51d4b3227e401f02"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "background-uimode-1.0.0-sources.jar",
          "url": "background-uimode-1.0.0-sources.jar",
          "size": 26327,
          "sha512": "7e2ad5aa8b058c49aec41b110c34ca927f132d8e75169db89d06446a00cd6592ae24b706f64f1be99e7aa5df77c7df4d74bc0ea7de5c4ed4230aeba3c4362031",
          "sha256": "2ab7090d62371561c16f8d09cf6b01eb0ec68afdf66feb9cbe2ce338fcbae5f6",
          "sha1": "6a8a74eee2d7baaaa65d63d209cd4e914942fe2d",
          "md5": "cd3854547d01b254dc8b9e234deb2218"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "background-uimode-1.0.0-javadoc.jar",
          "url": "background-uimode-1.0.0-javadoc.jar",
          "size": 362608,
          "sha512": "d6425af6fe08dc69b09481b0530c47a467561a6e5bd10dd262f63d201bba01d116e0fe595ccad57ab3f95e35ea87eebc140b8040101e403df91abc9fb84c264e",
          "sha256": "f825ae75a71a51bb535cb3788a049347f005555caa88d81355db5ab0b680f8fb",
          "sha1": "72bda795925ce3e5a0bd710a3fa5f46f7ce8f0bf",
          "md5": "7238316967d30f25ce5bf47036ac770c"
        }
      ]
    }
  ]
}
