{
  "formatVersion": "1.1",
  "component": {
    "group": "com.wogoo.android",
    "module": "uimode",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "uimode-1.0.3.aar",
          "url": "uimode-1.0.3.aar",
          "size": 105367,
          "sha512": "e22f0289e75f09b7255c4366090302d30975119374c59007dcbef407d49553b5d89e87ddd900405ed7449bdff60e801d0dc8de98b9b6bcf26ec0fad26e1a0ea8",
          "sha256": "1f2cdfad85419dae57acec984549249627c635a339138e24752e6d5ecaaf0e86",
          "sha1": "3dd0c14635a23347269ec5119f3045623894de28",
          "md5": "23c2d6f9cbac315ca2e33965f4fcdde7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "uimode-1.0.3.aar",
          "url": "uimode-1.0.3.aar",
          "size": 105367,
          "sha512": "e22f0289e75f09b7255c4366090302d30975119374c59007dcbef407d49553b5d89e87ddd900405ed7449bdff60e801d0dc8de98b9b6bcf26ec0fad26e1a0ea8",
          "sha256": "1f2cdfad85419dae57acec984549249627c635a339138e24752e6d5ecaaf0e86",
          "sha1": "3dd0c14635a23347269ec5119f3045623894de28",
          "md5": "23c2d6f9cbac315ca2e33965f4fcdde7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "uimode-1.0.3-sources.jar",
          "url": "uimode-1.0.3-sources.jar",
          "size": 47909,
          "sha512": "a468f5087a1d1467b29b48c744dd54608b1ef53dcbb613a91d1007fa356b228a3d5b9ad014d5acd34ca6b55b18b8954445aa2ade679a09e09aaedeb50de9fb37",
          "sha256": "05108d1d032acacfaccd199bf79218662d00d7983d625740360d7e5de952cd11",
          "sha1": "6eb1ca13d19522bb238b36ba3f2965f08dd4dd25",
          "md5": "09efb478ef9c3f79e087b3dd313ffa5e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "uimode-1.0.3-javadoc.jar",
          "url": "uimode-1.0.3-javadoc.jar",
          "size": 480866,
          "sha512": "be52eadf2014028b019dc690411750246c670b321be838f9ba14fa5e11f83caa899894a9c5cce75970b281aa0b032c82274b1ca9434d829e457cf0cf6d21e542",
          "sha256": "3621f056686b55b390512c277cd21065239c9fb45d5d842b84f81b1df6f130ee",
          "sha1": "7eb613424ba29b3ff46fe2d43d08bab33504b1f2",
          "md5": "7cbce473cbd4650508542992380c24a2"
        }
      ]
    }
  ]
}
